// <auto-generated />
using System;
using ASPNETBlank.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASPNETBlank.Migrations
{
    [DbContext(typeof(UrlShorterDbContext))]
    partial class UrlShorterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASPNETBlank.Models.UrlInfo", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<DateTime>("CreatonTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2048)");

                    b.Property<int>("UsesCount")
                        .HasColumnType("int");

                    b.HasKey("Hash");

                    b.ToTable("UrlInfos");

                    b.HasAlternateKey("Url").HasName("Url_IndexKey");
                });
#pragma warning restore 612, 618
        }
    }
}
